# Generated by Django 5.2.6 on 2025-09-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deptname", models.CharField(max_length=100)),
                ("hod", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
            ],
        ),
    ]
